### ISSUE TITLE
Conway Operators

### ISSUE THREAD

**Issue by pearswj** [meshmash/Plankton#24]
We have the dual. I'll shortly add truncation (#25). Why stop there?

http://en.wikipedia.org/wiki/Conway_polyhedron_notation

I love the way you can achieve the same _topology_ via different methods. Below, on the right is my truncation script and on the left is the result of applying dual-kis-dual (kis = stellate).

![image](https://cloud.githubusercontent.com/assets/121068/4591041/166f6bb2-5067-11e4-99bd-53183c6ad1c4.png)

**Comment by davbachman** [comment]
Are the Python scripts shown in the image available somewhere?

**Comment by pearswj** [comment]
Hi @davbachman, try this... [plankton_python_conway.gh.zip](https://github.com/meshmash/Plankton/files/798748/plankton_python_conway.gh.zip)

![plankton_conway](https://cloud.githubusercontent.com/assets/121068/23297276/d1a1e364-fa70-11e6-8e1c-72db28d9aaea.png)
