### ISSUE TITLE
Incorrect handling of overlapping edges?

### ISSUE THREAD

**Issue by NMO13** [meshmash/Plankton#33]
I'm not 100% sure but I think the following case is not correctly handled:

            PlanktonMesh pMesh = new PlanktonMesh();

            pMesh.Vertices.Add(0, 0, 0);
            pMesh.Vertices.Add(5, 0, 0);
            pMesh.Vertices.Add(5, 5, 0);
            pMesh.Vertices.Add(3, -5, 0);
            pMesh.Vertices.Add(7, 0, 0);

            pMesh.Faces.AddFace(0, 1, 2);
            pMesh.Faces.AddFace(0, 3, 4);

This looks something like this:

![zeichnung1](https://cloud.githubusercontent.com/assets/3988444/9738512/2af8527e-564c-11e5-824f-e10c4fe185f7.png)

But shouldn't it look like this?

![zeichnung2](https://cloud.githubusercontent.com/assets/3988444/9738658/d51fef1e-564c-11e5-9360-dd41adb30290.png)

**Comment by pearswj** [comment]
Not quite. You need to explicitly specify the fourth vertex if you want it to be included, i.e. `pMesh.Faces.AddFace(0, 3, 4, 1);`

**Comment by pearswj** [comment]
Not quite. You need to explicitly specify the fourth vertex if you want it to be included, i.e. `pMesh.Faces.AddFace(0, 3, 4, 1);`

![untitled](https://cloud.githubusercontent.com/assets/121068/9740533/2aa2cd6c-564d-11e5-9002-e427add869dd.png)

**Comment by NMO13** [comment]
Ok, yes makes sense. Thanks.

**Comment by pearswj** [comment]
No problem. Thanks for getting in touch all the same!
