### ISSUE TITLE
Getting Error Message Below when Compiling in VS2017 Community

### ISSUE THREAD

**Issue by tslewis** [meshmash/Plankton#48]
Hey Guys

wondering if someone else is getting the compile error below for y]the Plankton solution?

Thanks

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'out Q' to 'out Q'	PlanktonGh	C:\Users\Steve\Documents\GitHub\Plankton\src\PlanktonGh\GH_PlanktonMesh.cs	331	Active

![image](https://user-images.githubusercontent.com/7842764/53441589-03afd280-39bc-11e9-8eae-c61808e2259b.png)

**Comment by michaldengusiak** [comment]
Hi, I just used Visual Studio 2019 and connected to Rhino 6 and have the same error,
Any help would be appreciated,

![image](https://user-images.githubusercontent.com/26113670/70862583-1f2d9f00-1f36-11ea-884f-b02f9b0a2869.png)

**Comment by pearswj** [comment]
I'm looking into this! Am I right in assuming that you've updated the projects to target .NET Framework 4.5 and are referencing Grasshopper/RhinoCommon v6.*?

In the meantime I've updated the code to fetch Grasshopper v0.9.76 and RhinoCommon v5.12.* using Nuget, which should make compiling super easy.

**Comment by michaldengusiak** [comment]
@pearswj  thanks for looking at this,
I updated to  target .NET Framework 4.7.2 and  yes referencing directly
C:\Program Files\Rhino 6\System\RhinoCommon.dll
C:\Program Files\Rhino 6\Plug-ins\Grasshopper\GH_IO.dll
C:\Program Files\Rhino 6\Plug-ins\Grasshopper\Grasshopper.dll

**Comment by michaldengusiak** [comment]
@pearswj  thanks I can now rebuild all with VS2019
